### ISSUE TITLE
cbor error

### ISSUE THREAD

**Issue by DhruvaG2000** [SRA-VJTI/Wall-E_v2.2-beta#12]
If by any chance you face an error like ``cbor library not found`` once the installation completes, try switching to 
`` release/v4.2, origin/release/v4.2`` branch by 
* ```cd  %IDF_PATH% ``` 
* ``git checkout   origin/release/v4.2``

**Comment by laukik-hase** [comment]
@DhruvaG2000 The CMakeLists.txt for every component should include only the required components by that component. No redundant components should be present. Also, as notified earlier, switching to any non-stable ESP-IDF release is strictly prohibited for this project.
